### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by SalmanQureshi97** [Swrve/swrve-web-sdk#20]
I have double checked a million times but when initializing the SDK, there is an internal hit at : https://XXXX.identity.swrve.com/identify which fails and returns invalid api key. The key is correct.

**Comment by davidbreenwex** [comment]
Hi Salman, 

A good first step when seeing this error is to check that you are setting the correct stack when initializing Swrve. From the app_id I can see you should be pointing at the EU stack. 

If this doesn't fix the issue, please create a support ticket at support@swrve.com and I can organise a quick call to help debug the issue with you. 

Best, 
David

**Comment by SalmanQureshi97** [comment]
yeah that was it. It was commented out and it didnt say that it was a required option so I kept it commented. Best to update the docs. Thanks!!
