### ISSUE TITLE
Service Worker Registration fails

### ISSUE THREAD

**Issue by SalmanQureshi97** [Swrve/swrve-web-sdk#21]
![image](https://user-images.githubusercontent.com/45896078/176407812-764c1a4b-2ed7-45d5-843d-3f8273a1dc03.png)

Init with config auto registers SwrveWorker but it seems to be trying to register using a url instead of the service worker file. postinstall script tag did not solve this issue. ran it with http-server and locally with ssl.

**Comment by ThomasMcDonnell** [comment]
Hi @SalmanQureshi97, thanks for reporting the issue.
 
It does look as though the SDK is looking for the service worker at the root of the application correctly but it can not be found. It's hard to know exactly whats going on without being able to see your project structure or if you are using any bundlers such as webpack or frameworks eg React. 

You mention a http-server, are you sure that the service worker is available from the root ie if you drop the service worker into the public folder (or equivalent depending on your setup or how the project gets served) does that resolve the issue. If that does not work can you please supply a screen shot of the project structure, a sample of how you are passing the filename through config and the tools you are using eg any bundlers, frameworks etc so we might better replicate your issue? 

Thanks.

**Comment by SalmanQureshi97** [comment]
hi, so the swrveWorker file is not being moved by the post install script inside package.json. How I solved this is by passing serviceWorker attrbiute in the init function. Now this was not available in the docs. Also, i tried placing the swrveWorker in multiple directories but it still would not be able to find the file. If you look at the screenshot i put up in my initial issue post, you can see it is searching for an undefined file instead of swrveWorker. I guess the the documentation needs to be updated. 
![image](https://user-images.githubusercontent.com/45896078/177548643-bf7355b7-75fb-4c94-b6a6-176f190bd34e.png)

**Comment by SalmanQureshi97** [comment]
> hi, so the swrveWorker file is not being moved by the post install script inside package.json. How I solved this is by passing serviceWorker attrbiute in the init function. Now this was not available in the docs. Also, i tried placing the swrveWorker in multiple directories but it still would not be able to find the file. If you look at the screenshot i put up in my initial issue post, you can see it is searching for an undefined file instead of swrveWorker. I guess the the documentation needs to be updated. ![image](https://user-images.githubusercontent.com/45896078/177548643-bf7355b7-75fb-4c94-b6a6-176f190bd34e.png)

Also I am using angular 13

**Comment by ThomasMcDonnell** [comment]
Hi @SalmanQureshi97,

I am glad to see that you have resolved the issue and thanks for bringing this to our attention, at the minute that config (serviceWorker) key is a requirement for push and we will update our documentation to reflect this ASAP.

Regards
